[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "engine/text.lua"
pattern = "local old_letter = old_letters and old_letters[current_letter] or nil"
position = "before"
payload = '''
    if G.GAME and G.GAME.modifiers.cm_omit_digits then 
        if string.match(c, "%d") then c = '?' end
    end
'''
match_indent = true
overwrite = false

[[patches]]
[patches.pattern]
target = "engine/ui.lua"
pattern = "if self.config and self.config.text and not self.config.text_drawable then"
position = "before"
payload = '''
    if G.GAME and G.GAME.modifiers.cm_omit_digits and self.config.text then
        self.config.text = tostring(self.config.text):gsub('%d', '?')
    end
'''
match_indent = true
overwrite = false