return {
  name = "Wildin'",
  id = "c_mod_wild_1",
  rules = {
    custom = {
      { id = 'cm_wildin' },
      {
        id = "cm_credit",
        value = "Tuzzo",
      },
    },
    modifiers = {},
  },
  jokers = {},
  consumeables = {},
  vouchers = {
    { id = 'v_tarot_merchant' },
    { id = 'v_planet_merchant' },
  },
  deck = {
    type = "Challenge Deck",
    cards = {
      { s = "D", r = "A", e = "m_wild" },
      { s = "D", r = "2", e = "m_wild" },
      { s = "D", r = "3", e = "m_wild" },
      { s = "D", r = "4", e = "m_wild" },
      { s = "D", r = "5", e = "m_wild" },
      { s = "D", r = "6", e = "m_wild" },
      { s = "D", r = "7", e = "m_wild" },
      { s = "D", r = "8", e = "m_wild" },
      { s = "D", r = "9", e = "m_wild" },
      { s = "D", r = "T", e = "m_wild" },
      { s = "D", r = "J", e = "m_wild" },
      { s = "D", r = "Q", e = "m_wild" },
      { s = "D", r = "K", e = "m_wild" },
      { s = "C", r = "A", e = "m_wild" },
      { s = "C", r = "2", e = "m_wild" },
      { s = "C", r = "3", e = "m_wild" },
      { s = "C", r = "4", e = "m_wild" },
      { s = "C", r = "5", e = "m_wild" },
      { s = "C", r = "6", e = "m_wild" },
      { s = "C", r = "7", e = "m_wild" },
      { s = "C", r = "8", e = "m_wild" },
      { s = "C", r = "9", e = "m_wild" },
      { s = "C", r = "T", e = "m_wild" },
      { s = "C", r = "J", e = "m_wild" },
      { s = "C", r = "Q", e = "m_wild" },
      { s = "C", r = "K", e = "m_wild" },
      { s = "H", r = "A", e = "m_wild" },
      { s = "H", r = "2", e = "m_wild" },
      { s = "H", r = "3", e = "m_wild" },
      { s = "H", r = "4", e = "m_wild" },
      { s = "H", r = "5", e = "m_wild" },
      { s = "H", r = "6", e = "m_wild" },
      { s = "H", r = "7", e = "m_wild" },
      { s = "H", r = "8", e = "m_wild" },
      { s = "H", r = "9", e = "m_wild" },
      { s = "H", r = "T", e = "m_wild" },
      { s = "H", r = "J", e = "m_wild" },
      { s = "H", r = "Q", e = "m_wild" },
      { s = "H", r = "K", e = "m_wild" },
      { s = "S", r = "A", e = "m_wild" },
      { s = "S", r = "2", e = "m_wild" },
      { s = "S", r = "3", e = "m_wild" },
      { s = "S", r = "4", e = "m_wild" },
      { s = "S", r = "5", e = "m_wild" },
      { s = "S", r = "6", e = "m_wild" },
      { s = "S", r = "7", e = "m_wild" },
      { s = "S", r = "8", e = "m_wild" },
      { s = "S", r = "9", e = "m_wild" },
      { s = "S", r = "T", e = "m_wild" },
      { s = "S", r = "J", e = "m_wild" },
      { s = "S", r = "Q", e = "m_wild" },
      { s = "S", r = "K", e = "m_wild" },
    },
  },
  restrictions = {
    banned_cards = {
      { id = "c_chariot" },
      { id = "c_empress" },
      { id = "c_magician" },
      { id = "c_heirophant" },
      { id = "c_lovers" },
      { id = "c_justice" },
      { id = "c_devil" },
      { id = "c_tower" },
      { id = "c_familiar" },
      { id = "c_incantation" },
      { id = "c_grim" },
      {
        id = "p_standard_normal_1",
        ids = {
          "p_standard_normal_1",
          "p_standard_normal_2",
          "p_standard_normal_3",
          "p_standard_normal_4",
          "p_standard_jumbo_1",
          "p_standard_jumbo_2",
          "p_standard_mega_1",
          "p_standard_mega_2",
        },
      },
      { id = 'j_joker',
        ids = {
         "j_joker",
         "j_jolly",
         "j_zany",
         "j_mad",
         "j_sly",
         "j_wily",
         "j_clever",
         "j_stencil",
         "j_four_fingers",
         "j_mime",
         "j_banner",
         "j_mystic_summit",
         "j_loyalty_card",
         "j_8_ball",
         "j_dusk",
         "j_raised_fist",
         "j_fibonacci",
         "j_abstract",
         "j_delayed_grat",
         "j_pareidolia",
         "j_gros_michel",
         "j_even_steven",
         "j_odd_todd",
         "j_scholar",
         "j_business",
         "j_supernova",
         "j_ride_the_bus",
         "j_blackboard",
         "j_runner",
         "j_ice_cream",
         "j_dna",
         "j_splash",
         "j_blue_joker",
         "j_constellation",
         "j_hiker",
         "j_green_joker",
         "j_superposition",
         "j_todo_list",
         "j_cavendish",
         "j_card_sharp",
         "j_red_card",
         "j_seance",
         "j_vampire",
         "j_shortcut",
         "j_hologram",
         "j_vagabond",
         "j_baron",
         "j_cloud_9",
         "j_rocket",
         "j_obelisk",
         "j_photograph",
         "j_gift",
         "j_turtle_bean",
         "j_erosion",
         "j_reserved_parking",
         "j_mail",
         "j_to_the_moon",
         "j_fortune_teller",
         "j_juggler",
         "j_drunkard",
         "j_stone",
         "j_golden",
         "j_lucky_cat",
         "j_bull",
         "j_diet_cola",
         "j_trading",
         "j_flash",
         "j_popcorn",
         "j_ancient",
         "j_walkie_talkie",
         "j_selzer",
         "j_castle",
         "j_smiley",
         "j_campfire",
         "j_ticket",
         "j_mr_bones",
         "j_sock_and_buskin",
         "j_troubadour",
         "j_swashbuckler",
         "j_certificate",
         "j_hanging_chad",
         "j_rough_gem",
         "j_bloodstone",
         "j_arrowhead",
         "j_onyx_agate",
         "j_glass",
         "j_flower_pot",
         "j_blueprint",
         "j_wee",
         "j_oops",
         "j_idol",
         "j_seeing_double",
         "j_matador",
         "j_hit_the_road",
         "j_duo",
         "j_trio",
         "j_family",
         "j_order",
         "j_tribe",
         "j_invisible",
         "j_satellite",
         "j_shoot_the_moon",
         "j_bootstraps",
         "j_caino",
         "j_triboulet",
         "j_yorick",
         "j_luchador"
        },
      },
    },
    banned_tags = {
      { id = 'tag_standard' },
    },
    banned_other = {
      { id = "bl_hook", type = "blind" },
      { id = "bl_ox", type = "blind" },
      { id = "bl_house", type = "blind" },
      { id = "bl_wall", type = "blind" },
      { id = "bl_wheel", type = "blind" },
      { id = "bl_arm", type = "blind" },
      { id = "bl_fish", type = "blind" },
      { id = "bl_psychic", type = "blind" },
      { id = "bl_water", type = "blind" },
      { id = "bl_manacle", type = "blind" },
      { id = "bl_eye", type = "blind" },
      { id = "bl_mouth", type = "blind" },
      { id = "bl_serpent", type = "blind" },
      { id = "bl_needle", type = "blind" },
      { id = "bl_plant", type = "blind" },
      { id = "bl_pillar", type = "blind" },
      { id = "bl_tooth", type = "blind" },
      { id = "bl_flint", type = "blind" },
      { id = "bl_mark", type = "blind" },
      { id = "bl_final_leaf", type = "blind" },
      { id = "bl_final_heart", type = "blind" },
      { id = "bl_final_bell", type = "blind" },
      { id = "bl_final_vessel", type = "blind" },
    },
  },
}
