local challenge = {}
challenge.NAME = 'Expelled'
challenge.DESIGNER = 'ilikecheese'
challenge.DATE_CREATED = 240701
challenge.VERSION = '1.0.0'
challenge.DATA = {
    deck = {type = 'Challenge Deck'},
    rules = {
        custom = {
            {id = 'cm_expelled_1'},
            {id = 'cm_expelled_2'},
            {id = 'cm_expelled_3'},
            {id = 'cm_credit', value = 'ilikecheese'}
        }
    },
    restrictions = {
        banned_cards = {
            {id = 'j_mail'},
            {id = 'j_hallucination'},
            {id = 'j_gros_michel'},
            {id = 'j_cavendish'},
            {id = 'j_riff_raff'},
            {id = 'j_egg'},
            {id = 'j_photograph'},
            {id = 'j_hanging_chad'},
            {id = 'j_runner'},

            {id = 'j_chaos'},
            {id = 'j_smiley'},
            {id = 'j_drunkard'},
            {id = 'j_runner'},
            {id = 'j_todo_list'},
            {id = 'j_business'},
            {id = 'j_raised_fist'},
            {id = 'j_odd_todd'},
            {id = 'j_even_steven'},
            {id = 'j_faceless'},
            {id = 'j_wrathful_joker'},
            {id = 'j_gluttenous_joker'},
            {id = 'j_greedy_joker'},
            {id = 'j_lusty_joker'},
            {id = 'j_scary_face'},
            {id = 'j_ice_cream'},
            {id = 'j_abstract'},
            {id = 'j_half'},
            {id = 'j_mystic_summit'},
            {id = 'j_delayed_grat'},
            {id = 'j_golden'},
            {id = 'j_popcorn'},
            {id = 'j_juggler'},
            {id = 'j_fortune_teller'},

            {id = 'j_trading'},
            {id = 'j_shortcut'},
            {id = 'j_constellation'},
            {id = 'j_gift'},
            {id = 'j_trousers'},
            {id = 'j_bull'},
            {id = 'j_lucky_cat'},
            {id = 'j_bootstraps'},

            {id = 'j_cartomancer'},
            {id = 'j_troubadour'},
            {id = 'j_turtle_bean'},
            {id = 'j_rocket'},
            {id = 'j_midas_mask'},
            {id = 'j_vampire'},
            {id = 'j_fibonacci'},
            {id = 'j_arrowhead'},
            {id = 'j_onyx_agate'},
            {id = 'j_flash'},
            {id = 'j_hologram'},
            {id = 'j_ramen'},
            {id = 'j_card_sharp'},
            {id = 'j_mime'},
            {id = 'j_four_fingers'},
            {id = 'j_ceremonial'},
            {id = 'j_blackboard'},
            {id = 'j_selzer'},
            {id = 'j_oops'},

            {id = 'j_blueprint'},
            {id = 'j_invisible'},
            {id = 'j_yorick'},
            {id = 'j_caino'},
            {id = 'j_baseball'},
            {id = 'j_triboulet'},
            {id = 'j_stuntman'},

            {id = 'j_perkeo'},
            {id = 'j_chicot'},
            {id = 'j_wee'},
            {id = 'j_campfire'},
            {id = 'j_brainstorm'},
            {id = 'j_burnt'},
            {id = 'j_baron'},

            {id = 'c_immolate'},
            {id = 'c_soul'},
            {id = 'c_medium'},
            {id = 'c_temperance'},
            {id = 'c_deja_vu'},
            {id = 'c_fool'},
            {id = 'c_death'},
            {id = 'c_hanged_man'},
            {id = 'c_cryptid'},
            {id = 'c_justice'},
            {id = 'c_trance'},
            {id = 'c_aura'},
            {id = 'c_saturn'},
            {id = 'c_black_hole'},

            {id = 'c_ectoplasm'},
            {id = 'c_ceres'},
            {id = 'c_eris'},
            {id = 'c_neptune'},
            {id = 'c_magician'},
            {id = 'c_devil'},
            {id = 'c_talisman'},
            {id = 'c_hermit'},
            {id = 'c_emperor'},
            {id = 'c_wheel_of_fortune'},
            {id = 'c_chariot'},
            {id = 'c_high_priestess'},
            {id = 'c_sun'},
            {id = 'c_moon'},
            {id = 'c_world'},
            {id = 'c_star'},
        },
        banned_tags = {
            {id = 'tag_economy'},
            {id = 'tag_d_six'},
            {id = 'tag_coupon'},
            {id = 'tag_orbital'},
            
            {id = 'tag_top_up'},
            {id = 'tag_foil'},
            {id = 'tag_holo'},
            {id = 'tag_uncommon'},
            {id = 'tag_buffoon'},
            {id = 'tag_handy'},
            {id = 'tag_investment'},
        },
        banned_other = {
        }
    }
}
return challenge