local Challenge = {}
Challenge.NAME = "Oops! All Sixes!"
Challenge.DESIGNER = "Cheerio1101"
Challenge.DATE_CREATED = 240617 -- Y/M/D
Challenge.VERSION = "1.0.1"
Challenge.DATA = {
  rules = {
    custom = {
      { id = "cm_noshop"},
      { id = "no_reward"},
    },
    modifiers = {
      { id = "discards", value = 2 },
    },
  },
  jokers = {
    { id = "j_oops", eternal = true, edition = "negative" },
    { id = "j_sixth_sense", eternal = true, edition = "negative" },
  },
  consumeables = {},
  vouchers = {},
  deck = {
    --17 hearts/spades, 16 diamonds/clubs
    cards = {
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
    },
    type = "Challenge Deck",
  },
  restrictions = {
    banned_cards = {
      { id = "c_judgement" },
      { id = "c_wraith" },
      {
        id = "p_arcana_normal_1",
        ids = {
          "p_arcana_normal_1",
          "p_arcana_normal_2",
          "p_arcana_normal_3",
          "p_arcana_normal_4",
          "p_arcana_jumbo_1",
          "p_arcana_jumbo_2",
          "p_arcana_mega_1",
          "p_arcana_mega_2",
        },
      },
      {
        id = "p_buffoon_normal_1",
        ids = { "p_buffoon_normal_1", "p_buffoon_normal_2", "p_buffoon_jumbo_1", "p_buffoon_mega_1" },
      },
      {
        id = "p_spectral_normal_1",
        ids = { "p_spectral_normal_1", "p_spectral_normal_2", "p_spectral_jumbo_1", "p_spectral_mega_1" },
      },
    },
    banned_tags = {
      { id = "tag_top_up" },
      { id = "tag_buffoon" },
    },
    banned_other = {},
  },
}

return Challenge