local Challenge = {}
Challenge.NAME = "Withered Yaoi"
Challenge.DESIGNER = "Misty"
Challenge.DATE_CREATED = 240701 --Y/M/D
Challenge.VERSION = "1.0.0"
Challenge.DATA = {
  rules = {
    custom = {
      { id = 'cm_rand_card_destroy', value = 3 },
      { id = 'cm_draw_deck' },
    },
    modifiers = {
      { id = 'hands', value = 2 },
    },
  },
  jokers = {},
  consumeables = {},
  vouchers = {},
  deck = {
    type = "Challenge Deck",
    cards = {
      --80 cards, duped ace and J-6 in every suit
      { s = "H", r = "A" },
      { s = "H", r = "A" },
      { s = "H", r = "K" },
      { s = "H", r = "Q" },
      { s = "H", r = "J" },
      { s = "H", r = "J" },
      { s = "H", r = "T" },
      { s = "H", r = "T" },
      { s = "H", r = "9" },
      { s = "H", r = "9" },
      { s = "H", r = "8" },
      { s = "H", r = "8" },
      { s = "H", r = "7" },
      { s = "H", r = "7" },
      { s = "H", r = "6" },
      { s = "H", r = "6" },
      { s = "H", r = "5" },
      { s = "H", r = "4" },
      { s = "H", r = "3" },
      { s = "H", r = "2" },
      { s = "S", r = "A" },
      { s = "S", r = "A" },
      { s = "S", r = "K" },
      { s = "S", r = "Q" },
      { s = "S", r = "J" },
      { s = "S", r = "J" },
      { s = "S", r = "T" },
      { s = "S", r = "T" },
      { s = "S", r = "9" },
      { s = "S", r = "9" },
      { s = "S", r = "8" },
      { s = "S", r = "8" },
      { s = "S", r = "7" },
      { s = "S", r = "7" },
      { s = "S", r = "6" },
      { s = "S", r = "6" },
      { s = "S", r = "5" },
      { s = "S", r = "4" },
      { s = "S", r = "3" },
      { s = "S", r = "2" },
      { s = "D", r = "A" },
      { s = "D", r = "A" },
      { s = "D", r = "K" },
      { s = "D", r = "Q" },
      { s = "D", r = "J" },
      { s = "D", r = "J" },
      { s = "D", r = "T" },
      { s = "D", r = "T" },
      { s = "D", r = "9" },
      { s = "D", r = "9" },
      { s = "D", r = "8" },
      { s = "D", r = "8" },
      { s = "D", r = "7" },
      { s = "D", r = "7" },
      { s = "D", r = "6" },
      { s = "D", r = "6" },
      { s = "D", r = "5" },
      { s = "D", r = "4" },
      { s = "D", r = "3" },
      { s = "D", r = "2" },
      { s = "C", r = "A" },
      { s = "C", r = "A" },
      { s = "C", r = "K" },
      { s = "C", r = "Q" },
      { s = "C", r = "J" },
      { s = "C", r = "J" },
      { s = "C", r = "T" },
      { s = "C", r = "T" },
      { s = "C", r = "9" },
      { s = "C", r = "9" },
      { s = "C", r = "8" },
      { s = "C", r = "8" },
      { s = "C", r = "7" },
      { s = "C", r = "7" },
      { s = "C", r = "6" },
      { s = "C", r = "6" },
      { s = "C", r = "5" },
      { s = "C", r = "4" },
      { s = "C", r = "3" },
      { s = "C", r = "2" },
    }
  },
  restrictions = {
    banned_cards = {
      { id = "j_certificate" },
      { id = "j_dna" },
      { id = "j_marble" },
      { id = "c_cryptid" },
      { id = "c_familiar" },
      { id = "c_grim" },
      { id = "c_incantation" },
      { id = "v_magic_trick" },
      { id = "v_illusion" },
    },
    banned_tags = {},
    banned_other = {},
  },
}

return Challenge